name: BlogBot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours

jobs:
  run-blogbot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install feedparser

      - name: Run blogbot
        run: |
          python blogbot.py

      - name: Commit new posts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/*.md || echo "No new posts"
          git commit -m "Add new blog post" || echo "No changes to commit"
          git push
